version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: be_laravel
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Streamlit Application
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - DB_URI=mysql+pymysql://app_user:app_password@mysql:3306/be_laravel
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./.env:/app/.env:ro

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
