version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: be_laravel
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # LangGraph SQL Agent Client (Streamlit UI)
  client:
    build: ./client
    container_name: langgraph_client
    ports:
      - "8501:8501"
    environment:
      - DB_URI=mysql+pymysql://app_user:app_password@mysql:3306/be_laravel
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MCP_SERVER_URL=http://mcp_server:8000/mcp
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      mysql:
        condition: service_healthy
      mcp_server:
        condition: service_started
    networks:
      - app_network
    volumes:
      - ./.env:/app/.env:ro
      - ./client:/app
    restart: unless-stopped

  # MCP Server
  mcp_server:
    build: ./server
    container_name: mcp_server
    ports:
      - "8000:8000"
    environment:
      - DB_URI=mysql+pymysql://app_user:app_password@mysql:3306/be_laravel
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./.env:/app/.env:ro
      - ./server:/app
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
