version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "${VAULT_PORT}:8200"
    command: server -dev
    restart: unless-stopped
    networks:
      - vault-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-app
    env_file:
      - .env
    ports:
      - "${VAULT_API_PORT}:8000"
    depends_on:
      - vault
    restart: unless-stopped
    networks:
      - vault-network

volumes:
  vault-data:

networks:
  vault-network:
    driver: bridge
